In [16]:
import kagglehub

path = kagglehub.dataset_download("tmdb/tmdb-movie-metadata")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/tmdb/tmdb-movie-metadata/2.archive...

100%|██████████| 8.89M/8.89M [00:02<00:00, 3.66MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/tmdb/tmdb-movie-metadata/versions/2

In [19]:
import shutil

destination_path = "/content"
shutil.move(path, destination_path)

'/content/2'

In [4]:
import spacy
import pandas as pd
from collections import defaultdict

In [5]:
nlp = spacy.load("en_core_web_sm")

In [28]:
df = pd.read_csv('/content/2/tmdb_5000_movies.csv')

In [21]:
df.shape

(4803, 20)

In [22]:
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [25]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [29]:
df.drop(['homepage', 'tagline', 'original_language', 'vote_count', 'genres', 'budget', 'id', 'keywords', 'production_companies', 'popularity', 'production_countries', 'spoken_languages', 'revenue', 'original_title'], axis=1, inplace=True)

In [30]:
df.head()

,overview,release_date,runtime,status,title,vote_average
0,"In the 22nd century, a paraplegic Marine is di...",2009-12-10,162.0,Released,Avatar,7.2
1,"Captain Barbossa, long believed to be dead, ha...",2007-05-19,169.0,Released,Pirates of the Caribbean: At World's End,6.9
2,A cryptic message from Bond’s past sends him o...,2015-10-26,148.0,Released,Spectre,6.3
3,Following the death of District Attorney Harve...,2012-07-16,165.0,Released,The Dark Knight Rises,7.6
4,"John Carter is a war-weary, former military ca...",2012-03-07,132.0,Released,John Carter,6.1

In [31]:
df.isna().sum()

overview        3
release_date    1
runtime         2
status          0
title           0
vote_average    0
dtype: int64

In [33]:
df.dropna(inplace=True)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4799 entries, 0 to 4802
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   overview      4799 non-null   object
 1   release_date  4799 non-null   object
 2   runtime       4799 non-null   float64
 3   status        4799 non-null   object
 4   title         4799 non-null   object
 5   vote_average  4799 non-null   float64
dtypes: float64(2), object(4)
memory usage: 262.4+ KB

In [36]:
df['release_date'] = pd.to_datetime(df['release_date'])

In [43]:
def build_inverted_index(df):
  inverted_index = defaultdict(list)

  for idx, row in df.iterrows():
    docs = nlp(row['title'])
    tokens = [token.text for token in docs if not token.is_stop and not token.is_punct]
    title = " ".join(tokens)
    terms = str(title).lower().split()

    for term in terms:
      if idx not in inverted_index[term]:
        inverted_index[term].append(idx)

  return inverted_index

In [44]:
inverted_index = build_inverted_index(df)

In [51]:
def search_with_inverted_index(query, inverted_index, df, max_results = 5):
  query_terms = query.lower().split()
  matching_docs = set()

  for term in query_terms:
    if term in inverted_index:
      matching_docs.update(inverted_index[term])

  matching_docs = list(matching_docs)[:max_results]

  if matching_docs:
    print(f"\nDisplaying upto {max_results} results for search term {query}: ")
    for doc in matching_docs:
      row = df.iloc[doc]
      print(f"\nMovie title is: {row['title']}")
      print(f"Overview of movie is: {row['overview']}")
      print(f"Status is: {row['status']}")
      print(f"Release date: {row['release_date']}")
      print(f"Its runtime is: {row['runtime']}")
      print(f"Its Rating is: {row['vote_average']}")
      print("-" * 50)
  else:
    print(f"\nNo results found for movie {query}")

In [53]:
user_query = input("What movie/series would you like to know about: ")
search_with_inverted_index(user_query, inverted_index, df)

What movie/series would you like to know about: Pirates of the Caribbean

Displaying upto 5 results for search term Pirates of the Caribbean:

Movie title is: Pirates of the Caribbean: At World's End
Overview of movie is: Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems.
Status is: Released
Release date: 2007-05-19 00:00:00
Its runtime is: 169.0
Its Rating is: 6.9
--------------------------------------------------

Movie title is: Pirates of the Caribbean: The Curse of the Black Pearl
Overview of movie is: Jack Sparrow, a freewheeling 17th-century pirate who roams the Caribbean Sea, butts heads with a rival pirate bent on pillaging the village of Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her. But their seafaring mission is hardly simple.
Status is: Released
Release date: 2003-07-09 00:00:00
Its runtime is: 143.0
Its Rating is: 7.5
--------------------------------------------------

Movie title is: Pirates of the Caribbean: Dead Man's Chest
Overview of movie is: Captain Jack Sparrow works his way out of a blood debt with the ghostly Davey Jones, he also attempts to avoid eternal damnation.
Status is: Released
Release date: 2006-06-20 00:00:00
Its runtime is: 151.0
Its Rating is: 7.0
--------------------------------------------------

Movie title is: The Pirates! In an Adventure with Scientists!
Overview of movie is: The luxuriantly bearded Pirate Captain is a boundlessly enthusiastic, if somewhat less-than-successful, terror of the High Seas. With a rag-tag crew at his side, and seemingly blind to the impossible odds stacked against him, the Captain has one dream: to beat his bitter rivals Black Bellamy and Cutlass Liz to the much coveted Pirate of the Year Award. It’s a quest that takes our heroes from the shores of exotic Blood Island to the foggy streets of Victorian London. Along the way they battle a diabolical queen and team up with a haplessly smitten young scientist, but never lose sight of what a pirate loves best: adventure!
Status is: Released
Release date: 2012-03-12 00:00:00
Its runtime is: 88.0
Its Rating is: 6.4
--------------------------------------------------

Movie title is: Pirates of the Caribbean: On Stranger Tides
Overview of movie is: Captain Jack Sparrow crosses paths with a woman from his past, and he's not sure if it's love -- or if she's a ruthless con artist who's using him to find the fabled Fountain of Youth. When she forces him aboard the Queen Anne's Revenge, the ship of the formidable pirate Blackbeard, Jack finds himself on an unexpected adventure in which he doesn't know who to fear more: Blackbeard or the woman from his past.
Status is: Released
Release date: 2011-05-14 00:00:00
Its runtime is: 136.0
Its Rating is: 6.4
--------------------------------------------------